### ISSUE TITLE
【SWAP】界面上的一些TODO

### ISSUE THREAD

**Issue by guanchao71** [KodamaSakuno/bestswap-pools-interface#11]
主要
- [x] Swap页面缩窄之后“挖矿”入口消失了
- [x] Favicon需要替换（需要先从对方那边获取）
- [x] 导航的几个主要入口位置调整为居左显示
- [x] 需要将右上角菜单中和Uniswap相关的链接都删除
- [x] 移除 切换 Tokenlist的功能
![image](https://user-images.githubusercontent.com/10827774/95654759-c4a0a780-0b34-11eb-9e0c-31b37fd06cc8.png)

---
临时上线调整
- [ ] 临时移除“挖矿”入口的超链接

**Comment by Garfield550** [comment]
https://github.com/KodamaSakuno/uniswap-interface/pull/4

**Comment by Garfield550** [comment]
<img width="197" alt="Screen Shot 2020-10-10 at 9 31 39 PM" src="https://user-images.githubusercontent.com/3471836/95656300-07b44800-0b40-11eb-8381-abf7d7e66e89.png">
