### ISSUE TITLE
移除LPtoken进行到最后一步的时候无法Confirm

### ISSUE THREAD

**Issue by guanchao71** [KodamaSakuno/bestswap-pools-interface#18]
![image](https://user-images.githubusercontent.com/10827774/95857472-3cb5da00-0d8e-11eb-8477-967fd2f11e26.png)

**Comment by KodamaSakuno** [comment]
Fixed by https://github.com/KodamaSakuno/uniswap-interface/commit/ca6d94686b60082ca96ee0ed0bff1663c8d793f9
