### ISSUE TITLE
Need display APY.

### ISSUE THREAD

**Issue by lychees** [KodamaSakuno/bestswap-pools-interface#7]
<img width="961" alt="截屏2020-10-07 下午11 25 42" src="https://user-images.githubusercontent.com/2507027/95422602-74d39d80-08f4-11eb-9a6c-53d637584a33.png">

like 隔壁 pot finance ..

https://pot.finance/farms

<img width="974" alt="截屏2020-10-07 下午11 26 23" src="https://user-images.githubusercontent.com/2507027/95422659-8b79f480-08f4-11eb-8a3b-702c350e996f.png">

**Comment by Garfield550** [comment]
界面已经有了，需要上算法填空。

<img width="320" alt="Screen Shot 2020-10-09 at 9 31 47 PM" src="https://user-images.githubusercontent.com/3471836/95589094-dc195b00-0a76-11eb-9527-4c357f0f1ac2.png">
